# Generated by Django 3.1.7 on 2021-03-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_lipikar',
            field=models.BooleanField(default=False),
        ),
    ]
