# Generated by Django 3.1 on 2021-05-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210429_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 20, 47, 7, 848236)),
        ),
    ]
