# Generated by Django 3.1 on 2021-05-01 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210501_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 22, 14, 35, 62958)),
        ),
    ]
