# Generated by Django 3.1 on 2021-07-02 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210501_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Must be Unique & English', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 20, 58, 16, 526577)),
        ),
    ]
