# Generated by Django 3.1 on 2021-07-02 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210702_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 21, 2, 59, 120178)),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Must be Unique & English', unique=True),
        ),
    ]
