# Generated by Django 3.1.7 on 2021-04-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(max_length=15),
        ),
    ]
