# Generated by Django 3.1.7 on 2021-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210411_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
