# Generated by Django 3.1.7 on 2021-04-11 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_withdraw_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
