# Generated by Django 3.1 on 2021-04-15 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210415_2203'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feature_Post',
            new_name='FeaturePost',
        ),
    ]
