# Generated by Django 3.1 on 2021-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210415_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeaturePost',
            new_name='FeaturedPost',
        ),
    ]
